# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
  db_driver: orm # or mongodb or phpcr
  mappings:
    cour:
      uri_prefix: /images/files
      upload_destination: '%kernel.project_dir%/public/images/files'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true

    exercice:
      uri_prefix: /exercices
      upload_destination: '%kernel.project_dir%/public/exercices'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true

    examen:
      uri_prefix: /examens
      upload_destination: '%kernel.project_dir%/public/examens'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true

    user:
      uri_prefix: /user/images
      upload_destination: '%kernel.project_dir%/public/user/images'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true